const chartData = [
    {
      title: "Calendar connections per person",
      column1: "1",
      column2: "2",
      column3: "6",
      column4: "6",
      column5: "6",
    },
    {
      title:
        "Connect to Google, Office 365, Outlook and iCloud calenders",
      column1: true,
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Active event types",
      column1: "1",
      column2: "Unlimited",
      column3: "Unlimited",
      column4: "Unlimited",
      column5: "Unlimited",
    },
    {
      title: "Create unlimited one-on-one events",
      column1: true,
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Create meating polls",
      column1: "Unlimited",
      column2: "Unlimited",
      column3: "Unlimited",
      column4: "Unlimited",
      column5: "Unlimited",
    },
    {
      title: "Collective on-offs",
      column1: "-",
      column2: "-",
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Customize your booking link",
      column1: true,
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Create group events",
      column1: "-",
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Automated event notifications",
      column1: true,
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Send your invitee email reminders and follow-ups",
      column1: "-",
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Customise email notifications and reminders",
      column1: "-",
      column2: "-",
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Get meeting notification via text",
      column1: "-",
      column2: "-",
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Update your cancellation policy",
      column1: "-",
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Create automated workflows",
      column1: "-",
      column2: "-",
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Add links to your confirmation pages",
      column1: "-",
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "Redirect your invitees",
      column1: "-",
      column2: "-",
      column3: true,
      column4: true,
      column5: true,
    },
    {
      title: "View analytics and insights",
      column1: "-",
      column2: true,
      column3: true,
      column4: true,
      column5: true,
    },
  ]

  export default chartData